var annotated_dup =
[
    [ "midi", null, [
      [ "Midi", "classmidi_1_1_midi.html", null ],
      [ "MidiInterface", "classmidi_1_1_midi_interface.html", null ]
    ] ],
    [ "tester", null, [
      [ "Tester", "classtester_1_1_tester.html", null ]
    ] ],
    [ "validate", null, [
      [ "Arduino", "classvalidate_1_1_arduino.html", null ],
      [ "ArduinoMidiLibrary", "classvalidate_1_1_arduino_midi_library.html", null ],
      [ "Dict", "classvalidate_1_1_dict.html", null ]
    ] ],
    [ "AllBancosDialog", "class_all_bancos_dialog.html", null ],
    [ "AllBotonesDialog", "class_all_botones_dialog.html", null ],
    [ "AllConfiguracionesDialog", "class_all_configuraciones_dialog.html", null ],
    [ "AllInstrumentosDialog", "class_all_instrumentos_dialog.html", null ],
    [ "Banco", "class_banco.html", null ],
    [ "BancoDialog", "class_banco_dialog.html", null ],
    [ "Boton", "class_boton.html", null ],
    [ "BotonDialog", "class_boton_dialog.html", null ],
    [ "Configuracion", "class_configuracion.html", null ],
    [ "ConfiguracionDialog", "class_configuracion_dialog.html", null ],
    [ "Connector", "class_connector.html", null ],
    [ "CustomItemWidget", "class_custom_item_widget.html", null ],
    [ "DefaultPlatform", "struct_default_platform.html", null ],
    [ "DefaultSerialSettings", "struct_default_serial_settings.html", null ],
    [ "DefaultSettings", "struct_default_settings.html", null ],
    [ "Dialog", "class_dialog.html", null ],
    [ "Instrumento", "class_instrumento.html", null ],
    [ "InstrumentoDialog", "class_instrumento_dialog.html", null ],
    [ "MainWindow", "class_main_window.html", null ],
    [ "Message", "struct_message.html", "struct_message" ],
    [ "MidiInputCallbacks", "class_midi_input_callbacks.html", null ],
    [ "MidiInterface", "class_midi_interface.html", "class_midi_interface" ],
    [ "MidiNote", "struct_midi_note.html", null ],
    [ "MidiNoteList", "class_midi_note_list.html", "class_midi_note_list" ],
    [ "NewBancoDialog", "class_new_banco_dialog.html", null ],
    [ "NewConfiguracionesDialog", "class_new_configuraciones_dialog.html", null ],
    [ "NewInstrumentosDialog", "class_new_instrumentos_dialog.html", null ],
    [ "PreferencesDialog", "class_preferences_dialog.html", null ],
    [ "ProyectoConfiguraciones", "class_proyecto_configuraciones.html", null ],
    [ "ProyectoConfiguracionesDialog", "class_proyecto_configuraciones_dialog.html", null ],
    [ "ProyectoInstrumentos", "class_proyecto_instrumentos.html", null ],
    [ "ProyectoInstrumentosDialog", "class_proyecto_instrumentos_dialog.html", null ],
    [ "QewTreeViewDialog", "class_qew_tree_view_dialog.html", "class_qew_tree_view_dialog" ],
    [ "QewTreeViewDialogEmpty", "class_qew_tree_view_dialog_empty.html", null ],
    [ "QewTreeViewDialogForm", "class_qew_tree_view_dialog_form.html", null ],
    [ "QVariantPtr", "class_q_variant_ptr.html", null ],
    [ "RingBuffer", "class_ring_buffer.html", null ],
    [ "RPN", "struct_r_p_n.html", null ],
    [ "SeleccionCanalDialog", "class_seleccion_canal_dialog.html", null ],
    [ "SeleccionInstrumentosDialog", "class_seleccion_instrumentos_dialog.html", null ],
    [ "SeleccionPanningDialog", "class_seleccion_panning_dialog.html", null ],
    [ "SeleccionVolumenDialog", "class_seleccion_volumen_dialog.html", null ],
    [ "SerialMIDI", "class_serial_m_i_d_i.html", null ],
    [ "SerialMock", "class_serial_mock.html", null ],
    [ "State", "class_state.html", "class_state" ],
    [ "Thru", "struct_thru.html", "struct_thru" ],
    [ "Value", "struct_value.html", null ],
    [ "VariableSettings", "struct_variable_settings.html", null ],
    [ "VariableSysExSettings", "struct_variable_sys_ex_settings.html", null ]
];