var dir_f1e3d4b0ea21d3fde41b83660a5d184c =
[
    [ "arduino", "dir_6f19f925b13d473b7e0a71fccc408684.html", "dir_6f19f925b13d473b7e0a71fccc408684" ],
    [ "instalar", "dir_6ef1c741f9927058a807b67e7924fe7a.html", "dir_6ef1c741f9927058a807b67e7924fe7a" ],
    [ "allbancosdialog.h", "allbancosdialog_8h_source.html", null ],
    [ "allbotonesdialog.h", "allbotonesdialog_8h_source.html", null ],
    [ "allconfiguracionesdialog.h", "allconfiguracionesdialog_8h_source.html", null ],
    [ "allinstrumentosdialog.h", "allinstrumentosdialog_8h_source.html", null ],
    [ "banco.h", "banco_8h_source.html", null ],
    [ "bancodialog.h", "bancodialog_8h_source.html", null ],
    [ "boton.h", "boton_8h_source.html", null ],
    [ "botondialog.h", "botondialog_8h_source.html", null ],
    [ "configuracion.h", "configuracion_8h_source.html", null ],
    [ "configuraciondialog.h", "configuraciondialog_8h_source.html", null ],
    [ "connector.h", "connector_8h_source.html", null ],
    [ "dialog.h", "dialog_8h_source.html", null ],
    [ "elementolistaconfig.h", "elementolistaconfig_8h_source.html", null ],
    [ "instrumento.h", "instrumento_8h_source.html", null ],
    [ "instrumentoDialog.h", "instrumento_dialog_8h_source.html", null ],
    [ "mainwindow.h", "mainwindow_8h_source.html", null ],
    [ "newbancodialog.h", "newbancodialog_8h_source.html", null ],
    [ "newconfiguracionesdialog.h", "newconfiguracionesdialog_8h_source.html", null ],
    [ "newinstrumentosdialog.h", "newinstrumentosdialog_8h_source.html", null ],
    [ "preferencesdialog.h", "preferencesdialog_8h_source.html", null ],
    [ "proyectoconfiguraciones.h", "proyectoconfiguraciones_8h_source.html", null ],
    [ "proyectoconfiguracionesdialog.h", "proyectoconfiguracionesdialog_8h_source.html", null ],
    [ "proyectoInstrumentos.h", "proyecto_instrumentos_8h_source.html", null ],
    [ "proyectoinstrumentosdialog.h", "proyectoinstrumentosdialog_8h_source.html", null ],
    [ "qewtreeviewdialog.h", "qewtreeviewdialog_8h_source.html", null ],
    [ "qewtreeviewdialogform.h", "qewtreeviewdialogform_8h_source.html", null ],
    [ "qvariantptr.h", "qvariantptr_8h_source.html", null ],
    [ "seleccioncanaldialog.h", "seleccioncanaldialog_8h_source.html", null ],
    [ "seleccioninstrumentosdialog.h", "seleccioninstrumentosdialog_8h_source.html", null ],
    [ "seleccionpanningdialog.h", "seleccionpanningdialog_8h_source.html", null ],
    [ "seleccionvolumendialog.h", "seleccionvolumendialog_8h_source.html", null ]
];